### ISSUE TITLE
Invalid yaml is generated by anonymizer

### ISSUE THREAD

**Issue by chinghuachen** [ansible/anonymizer#44]
### Description

The PII masking can create illegal yaml.

#### Example 1
`config_reverseproxy_oauth_password: "passw0rd"`
to
`config_reverseproxy_oauth_password: "{{ config_reverseproxy_oauth_password }}""passw0rd"`
instead of
`config_reverseproxy_oauth_password: "{{ config_reverseproxy_oauth_password }}"`

#### Example 2
`dir_sd_password: "{{ current_sd_password.stdout }}"`
to
`dir_sd_password: ""{{ dir_sd_password }}"current_sd_password.stdout }}"`

**Comment by chinghuachen** [comment]
apparently we ran the anonymizer in “text” mode rather than “yaml” mode and this error doesn’t happen in “yaml” mode. So maybe this is not a bug after all… based on your design

**Comment by goneri** [comment]
I cannot reproduce the problem:

```console
$ cat sample
---
config_reverseproxy_oauth_password: "passw0rd"
dir_sd_password: "{{ current_sd_password.stdout }}"
$ ansible-anonymizer sample
---
config_reverseproxy_oauth_password: "{{ config_reverseproxy_oauth_password }}"
dir_sd_password: "{{ dir_sd_password }}"
$ ansible-anonymizer --format yaml sample
{'config_reverseproxy_oauth_password': '{{ config_reverseproxy_oauth_password }}', 'dir_sd_password': '{{ current_sd_password.stdout }}'}
```

I suspect the problem is coming from another part of the document, like a missing `"` for instance.
